### ISSUE TITLE
Custom Toolbar Button

### ISSUE THREAD

**Issue by sineld** [marshmallow-packages/nova-tinymce#142]
Hi friend,

Is it possible to add custom toolbar buttons like it is described here: https://www.tiny.cloud/docs-4x/demo/custom-toolbar-button/

Thanks.

**Comment by stefvanesch** [comment]
@sineld sorry for the late reply! We will look into this tomorrow. Would be an awesome feature. We will keep you posted!

**Comment by sineld** [comment]
@stefvanesch Thank you so much. Looking forward to hearing for this feature.

**Comment by sineld** [comment]
Thank you for quick update. I have added buttons but they are not visible. I've published the assets:

  php artisan vendor:publish --provider="Marshmallow\Nova\TinyMCE\FieldServiceProvider" --tag="resources"

```
TinyMCE::make(__('Content'), 'content')
    ->rules('required', 'min:10')
    ->alwaysShow()
    ->hideFromDetail()
    ->buttons([
        'Name' => '[NAME]',
        'Surname' => '[SURNAME]',
        'Email' => '[EMAIL]',
        'Code' => '[CODE]',
    ]),
```
![TinyMCE](https://user-images.githubusercontent.com/445349/168816703-9fd12970-77ec-4f66-9480-4b6e3dedbf7f.jpg)

**Comment by LTKort** [comment]
Hi, have you published the config as well? If so you need to add ‘my_buttons’ to the plugins and the toolbar

**Comment by LTKort** [comment]
@sineld Sure, it's done & tagged
